#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# ensure that we have a composing manager running
xcompmgr -cFr0 &

# ensure that our synergy server is running
synergys

# start the dropbox deamon
dropboxd &

# enable the numlock while logging in
numlockx &

# start the screensaver daemon
xscreensaver -no-splash &

# start the window manager
exec awesome
