alias ll="clear && ls -l --color=auto"
alias la="clear && ls -la --color=auto"
alias pac="yaourt"
alias gits="clear && git status"
alias tigger="tig --all"
alias open="xdg-open"
alias grep="grep -i --color=auto"
alias nb="ipython2 notebook --pylab=inline"
alias dev="terminator -l programming"

# if we're running on MacOS, change some unsupported aliases
if [ "$(uname -s)" == "Darwin" ]; then
	alias ll="clear && ls -l"
	alias la="clear && ls -la"
	unalias open
	unalias tigger
	unalias pac
fi
