alias ll="clear && ls -lh --color=auto"
alias la="clear && ls -lha --color=auto"
alias pac="yaourt"
alias gits="clear && git status"
alias tigger="tig --all"
alias open="xdg-open"
alias grep="grep -i --color=auto"
alias nb="ipython2 notebook --pylab=inline"
alias dev="terminator -l programming"
alias tl="clear && task long && task calendar"

# if we're running on MacOS, change some unsupported aliases
if [ "$(uname -s)" == "Darwin" ]; then
	alias ll="clear && ls -lG"
	alias la="clear && ls -laG"
	unalias open
	unalias tigger
	unalias pac
fi
