#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# ensure that we have a composing manager running
# compton --config ~/.config/awesome/userdir/compton -b

# ensure that our synergy server is running
synergys

# start the dropbox deamon
dropboxd &

# start the ownCloud client
# owncloud & # TODO: 2013-05-21 the current version needs too much RAM

# start the SparkleShare client
sparkleshare start &

# enable the numlock while logging in
numlockx &

# start the window manager
exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
